### ISSUE TITLE
Traceback trying to export to TXT

### ISSUE THREAD

**Issue by sknorr** [gaois/terminologue#59]
Trying to use the TXT export button at the bottom of the sidebar, Terminologue trips ... apparently over a lack of examples?

```
[dir]/terminologue/website/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'map' of undefined
    at [dir]/terminologue/shared/entry-to-txt.js:88:28
    at Array.map (<anonymous>)
    at doExamples ([dir]/terminologue/shared/entry-to-txt.js:87:18)
    at [dir]/terminologue/shared/entry-to-txt.js:46:40
    at Array.map (<anonymous>)
    at Object.doEntry ([dir]/terminologue/shared/entry-to-txt.js:40:16)
    at [dir]/terminologue/website/ops.js:2420:31
    at Array.map (<anonymous>)
    at Statement.<anonymous> ([dir]/terminologue/website/ops.js:2417:16)
--> in Database#all('select id, json from entries where id in (5137)', { '$ids': [Array] }, [Function
 (anonymous)])
    at [dir]/terminologue/website/ops.js:2415:12
    at Statement.<anonymous> ([dir]/terminologue/website/ops.js:456:7) {
  __augmented: true
}
```

**Comment by michmech** [comment]
Fixed by commit 3da99e8. Turns out it was trivial.
